name: build  # Name of the conda environment
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - ipykernel
  - ipywidgets
  - numpy
  - matplotlib
  - pandas
  - pytorch
  - cpuonly
  - typer[all]
  # - pip:  
  #   - jax[cuda12_pip]
  #   - --find-links https://storage.googleapis.com/jax-releases/jax_cuda_releases.html